### PR TITLE
Upload API

### PR DESCRIPTION
**Pull request by MichaelCurrie**
Please review this PR at your convenience.  It's a class, `Deposition`, to load and create Zenodo depositions as per https://zenodo.org/dev#restapi-quick.

It's not 100% complete but it handles my use case and it's complete enough that I believe it would be useful for others.

I've added a bit of documentation, testing, and I also incremented the version number, so if this is all acceptable to you I'd appreciate if you'd push out a new release to PyPI when all is said and done.

Cheers!

### CODE REVIEW

**Comment by MichaelCurrie** [comment]
Give me a sec to fix the CI check.  I'll do that tmrw.

**Comment by MichaelCurrie** [comment]
OK, fixed.

**Comment by jonathansick** [comment]
Sweet! Thank you. I'll take a closer look in a bit, but in the meantime, do you think you could squash the commits down to logical units and force-push back to your branch?

**Comment by MichaelCurrie** [comment]
OK, good idea.  Done.  History has been altered.  And I've emerged back in my own time, at almost the same instant that I left.

**Comment by MichaelCurrie** [comment]
Hi @jonathansick, can you let me know if your intention is to eventually merge this code or if you've decided it's not right for your repo?  That will help guide me for next steps with my workflow.

Thanks

**Comment by jonathansick** [comment]
Hi @MichaelCurrie, I think the best route for you is to published your fork and this PR yourself on PyPI. We're not sure about how we're going forward with Zenodo here, and you're right, we don't want LSST's / zenodio's development schedule to get in the way of shipping your stuff.

**Comment by MichaelCurrie** [comment]
OK thanks for the feedback.  I will close this and push to master on my fork.

**Pull request closed without merging**
